config/routes.rb
Fortunka::Application.routes.draw do

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  resources :fortunes

 
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
belongs_to :user
validates :provider, :uid, :presence => true

def self.find_from_hash(hash)
  find_by_provider_and_uid(hash['provider'], hash['uid'])
end

def self.create_from_hash(hash, user = nil)
  user ||= User.create_from_hash!(hash)
  Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fortune
  validates :author, :presence => true
  validates :body, :presence => true
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
  validates :body, :presence => true
  validates_length_of :body, :in => 2..70
  validates_length_of :source, :in => 2..30
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["user_info"]["name"]
  end
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery  
helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/comments_controller.rb
commentable = Post.create
commentable.comments.create(:title => "First comment.", :comment => "This is the first comment.")

commentable = Post.find(1)
comments = commentable.comments.recent.limit(10).all 

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  # GET /fortunes
  def index
    @fortunes = Fortune.page(params[:page]).per(5)
    
  end

  # GET /fortunes/1
  def show
  @fortune = Fortune.find(params[:id])
  end

  # GET /fortunes/new
  def new
    @fortune = Fortune.new
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  def create
    @fortune = Fortune.new(params[:fortune])

    if @fortune.save
      redirect_to @fortune, notice: 'Fortune was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /fortunes/1
  def update
    @fortune = Fortune.find(params[:id])

    if @fortune.update_attributes(params[:fortune])
      redirect_to @fortune, notice: 'Fortune was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /fortunes/1
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy
    redirect_to fortunes_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
  auth = request.env["omniauth.auth"]
  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
  session[:user_id] = user.id
  redirect_to '/fortunes', :notice => "Signed in!"
end

def destroy
  session[:user_id] = nil
  redirect_to '/fortunes', :notice => "Signed out!"
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/helpers/layout_helper.rb
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  def show_title?
    @show_title
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for [@fortune, @comment] do |f| %>
  <%= f.input :author, :input_html => {:size => 40} %>
  <%= f.input :body, :input_html => {:rows => 4, :cols => 40} %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<% title "Editing comment" %>
<%= render :partial => 'form' %>
<p class="links clear">
  <%= link_to 'Show Fortune', @comment.fortune %>
</p>

app/views/comments/new.html.erb
<% title "New comment" %>
<%= render :partial => 'form' %>
<p class="links clear"><%= link_to 'Back', @comment.fortune %></p>

app/views/fortunes/_form.html.erb
<%= simple_form_for(@fortune) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :source %>
    <%= f.input :body %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fortunes/edit.html.erb
<% title "Editing fortune" %>

<div class="form edit">
  <%= render 'form' %>
  <div class="link">
    <%= link_to 'Show', @fortune %> |
    <%= link_to 'Back', fortunes_path %>
  </div>
</div>

app/views/fortunes/index.html.erb
<% title "All fortunes" %>
<div class="sign">
<% if current_user %>
  Welcome <%= current_user.name %>!
  <%= link_to "Sign Out", signout_path %>
<% else %>
  <%= link_to "Sign in with Twitter", "/auth/twitter" %>
<% end %>
  </div>
<br/>
<div class="newText">
 <%= link_to 'New Fortune', new_fortune_path %>
</div>
<br/><br/>
<% @fortunes.each do |fortune| %>

<article class="index">
 


  <div class="attribute">
    <span class="name">Source</span>
    <span class="value"><%= fortune.source %></span>
  </div>
    <div class="attribute">
    <span class="name">Body</span>
    <span class="value"><%= fortune.body %></span>
  </div>
    <div class="links">
    <%= link_to 'Show', fortune %> |
    <%= link_to 'Edit', edit_fortune_path(fortune) %> |
    <%= link_to 'Destroy', fortune, confirm: 'Are you sure?', method: :delete %>
  </div>
</article>
<% end %>

<div class="link">
 




  <%= paginate @fortunes %>




</div>

app/views/fortunes/new.html.erb
<% title "New fortune" %>

<div class="form new">
  <%= render 'form' %>
  <div class="link">
    <%= link_to 'Back', fortunes_path %>
  </div>
</form>

app/views/fortunes/show.html.erb
<% if notice -%>
<div id="notice"><%= notice %></div>
<% end -%>

<article class="single">
  <div class="attribute">
    <span class="name">Source</span>
    <span class="value"><%= @fortune.source %></span>
  </div>
  <div class="attribute">
    <span class="name">Body</span>
    <span class="value"><%= @fortune.body %></span>
  </div>
  <div class="link">
    <%= link_to 'Edit', edit_fortune_path(@fortune) %> |
    <%= link_to 'Back', fortunes_path %>
  </div>
</article>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= content_for?(:title) ? yield(:title) : "Fortunka" %></title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <%= stylesheet_link_tag "application" %>
  
  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build incl. Respond.js
       Respond is a polyfill for min/max-width media queries. Modernizr enables HTML5 elements & feature detects; 
       for optimal performance, create your own custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
     <%= content_tag :h1, "Fortunka" %>
  </header>
  <div role="main">
    <%= content_tag :h1, yield(:title) if show_title? %>
    <%= yield %>
  </div>
  <footer>
  </footer>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

</body>
</html>